sudo: required
dist: bionic
language: ruby
rvm:
  - 2.6

script:
  - bundle install
  - make run-rspec

after_success:
  - curl https://deepsource.io/cli | sh
  - ./bin/deepsource report --analyzer test-coverage --key ruby --value-file ./coverage/.resultset.json
